version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMDB_V3_API_KEY: ${TMDB_V3_API_KEY}
    environment:
      - VITE_APP_TMDB_V3_API_KEY=${TMDB_V3_API_KEY}
      - VITE_APP_API_ENDPOINT_URL="https://api.themoviedb.org/3"
    ports:
      - "80:80"  # Change this if needed
    restart: always

